import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import {
  FaTwitter,
  FaInstagram,
  FaFacebookSquare,
  FaPhone,
  FaEnvelope,
  FaLinkedin,
} from "react-icons/fa";
import { FaHospital } from "react-icons/fa6";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: {
    default: "MedFinder",
    template: "%s | MedFinder",
  },
  description: "Generated by MedFinder",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className=" p-4">
          
          <nav className="flex flex-row gap-2 justify-between text-center items-center stick border-b border-blue-100">
            <div className="logo my-2 p-2">
              <h1 className=" text-xl md:text-3xl font-bold cursor-pointer ">
                <Link href="/">MedFinder</Link>
              </h1>
            </div>
            <div className="flex items-center">
              <div className="  md:h-10 mx-auto mt-2">
                <label className="swap swap-rotate">
                  {/* this hidden checkbox controls the state */}
                  <input
                    type="checkbox"
                    className="theme-controller hidden"
                    value="light"
                  />

                  {/* sun icon */}
                  <svg
                    className="swap-off h-6 w-10 fill-current"
                    xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 24 24"
                  >
                    <path d="M5.64,17l-.71.71a1,1,0,0,0,0,1.41,1,1,0,0,0,1.41,0l.71-.71A1,1,0,0,0,5.64,17ZM5,12a1,1,0,0,0-1-1H3a1,1,0,0,0,0,2H4A1,1,0,0,0,5,12Zm7-7a1,1,0,0,0,1-1V3a1,1,0,0,0-2,0V4A1,1,0,0,0,12,5ZM5.64,7.05a1,1,0,0,0,.7.29,1,1,0,0,0,.71-.29,1,1,0,0,0,0-1.41l-.71-.71A1,1,0,0,0,4.93,6.34Zm12,.29a1,1,0,0,0,.7-.29l.71-.71a1,1,0,1,0-1.41-1.41L17,5.64a1,1,0,0,0,0,1.41A1,1,0,0,0,17.66,7.34ZM21,11H20a1,1,0,0,0,0,2h1a1,1,0,0,0,0-2Zm-9,8a1,1,0,0,0-1,1v1a1,1,0,0,0,2,0V20A1,1,0,0,0,12,19ZM18.36,17A1,1,0,0,0,17,18.36l.71.71a1,1,0,0,0,1.41,0,1,1,0,0,0,0-1.41ZM12,6.5A5.5,5.5,0,1,0,17.5,12,5.51,5.51,0,0,0,12,6.5Zm0,9A3.5,3.5,0,1,1,15.5,12,3.5,3.5,0,0,1,12,15.5Z" />
                  </svg>

                  {/* moon icon */}
                  <svg
                    className="swap-on h-6 w-10 fill-current"
                    xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 24 24"
                  >
                    <path d="M21.64,13a1,1,0,0,0-1.05-.14,8.05,8.05,0,0,1-3.37.73A8.15,8.15,0,0,1,9.08,5.49a8.59,8.59,0,0,1,.25-2A1,1,0,0,0,8,2.36,10.14,10.14,0,1,0,22,14.05,1,1,0,0,0,21.64,13Zm-9.5,6.69A8.14,8.14,0,0,1,7.08,5.22v.27A10.15,10.15,0,0,0,17.22,15.63a9.79,9.79,0,0,0,2.1-.22A8.11,8.11,0,0,1,12.14,19.73Z" />
                  </svg>
                </label>
              </div>
              <ul className="md:flex md:flex-row md:items-center rounded-md mb-2 z-[1] md:z-auto md:static left-0 absolute w-full md:w-auto md:py-0 py-4 md:pl-0 pl-7  md:mt-0 mt-8  top-[-400px] transition-all ease-in duration-500">
                <li className="mx-2 my-6 md:my-0 active:text-blue-400 duration-600 hover:font-bold  hover:border hover:border-blue-200 p-2 rounded-md   ">
                  <Link href="/">Home</Link>
                </li>

                <li className="mx-82my-6 md:my-0 active:text-blue-400 duration-600 hover:font-bold  hover:border hover:border-blue-200 p-2 rounded-md  ">
                  <Link href="/about">About</Link>
                </li>

                <li className="mx-2 my-6 md:my-0 active:text-blue-400 duration-600 hover:font-bold  hover:border hover:border-blue-200 p-2 rounded-md ">
                  <Link href="/contact">Contact us</Link>
                </li>

                <div className="sign-in inline my-2 mr-2 items-center text-lg p-2 hover:bg-blue-200 hover:text-black hover:font-bold md:text-center rounded-md active:transition delay-150 ease-in-out">
                  <button>
                    <Link href="/login">Sign-In</Link>
                  </button>
                </div>
              </ul>
            </div>

            <label className="btn btn-circle swap swap-rotate md:hidden">
              {/* this hidden checkbox controls the state */}
              <input type="checkbox" className="md:hidden" />

              {/* hamburger icon */}
              <svg
                className="swap-off fill-current"
                xmlns="http://www.w3.org/2000/svg"
                width="32"
                height="32"
                viewBox="0 0 512 512"
              >
                <path d="M64,384H448V341.33H64Zm0-106.67H448V234.67H64ZM64,128v42.67H448V128Z" />
              </svg>

              {/* close icon */}
              <svg
                className="swap-on fill-current"
                xmlns="http://www.w3.org/2000/svg"
                width="32"
                height="32"
                viewBox="0 0 512 512"
              >
                <polygon
                  points="400 145.49 366.51 112 256 222.51 145.49 112 112 145.49 222.51 256 112
                 366.51 145.49 400 256 289.49 366.51 400 400 366.51 289.49 256 400 145.49"
                />
              </svg>
            </label>
          </nav>
        </header>
        {children}
        <footer className="footer bg-base-200 text-base-content text-center p-10">
          <aside>
            <div className="inline-flex items-center">
              <FaHospital height={80} /> MedFinder
            </div>

            <p>
              <br />
              Providing reliable guide to latest health development and
              Locations.
            </p>
          </aside>
          <nav>
            <h6 className="footer-title">Socials</h6>
            <a className="link link-hover inline-flex items-center gap-2">
              <FaTwitter /> Twitter
            </a>
            <a className="link link-hover inline-flex items-center gap-2">
              <FaInstagram /> Instagram
            </a>
            <a className="link link-hover inline-flex items-center gap-2">
              <FaLinkedin /> LinkedIn
            </a>
            <a className="link link-hover inline-flex items-center gap-2">
              <FaFacebookSquare /> FaceBook
            </a>
          </nav>
          <nav>
            <h6 className="footer-title">MedFinder</h6>
            <a className="link link-hover">About us</a>
            <a className="link link-hover">Contact</a>
            <a className="link link-hover inline-flex items-center gap-2">
              <FaPhone />
              To-Free 1-800-med-finder
            </a>
            <a className="link link-hover inline-flex items-center gap-2">
              <FaEnvelope />
              support@medfinder.com
            </a>
          </nav>
          <nav>
            <h6 className="footer-title">Legal</h6>
            <a className="link link-hover">Terms of use</a>
            <a className="link link-hover">Privacy policy</a>
            <a className="link link-hover">Cookie policy</a>
          </nav>

          <div>
            <p>&copy;2024 All right reserved.</p>
            <div>Developed by Samuel Ogbaje</div>
          </div>
        </footer>
      </body>
    </html>
  );
}
